### PR TITLE
Add remaining gimmick table names & challenge battle xrefs

### PR DESCRIPTION
**Pull request by RoccoDev**
For some reason, DLC2 has a `gmk` folder that isn't present in the main ROM (the game still uses `gmk_r`). It contains some lvb files for all maps (including some debug and test maps) with cleartext strings.   
Specifically, `ma90gmk_dlc02.lvb` has all the gimmick type names scattered around in alphabetical order.

This also adds some xrefs and name references to the list of challenge battles.

### CODE REVIEW

**Comment by RoccoDev** [comment]
I've also made some more changes, namely I moved gimmick hashes to their own hash calculator so updating them is easier and less error-prone.  
I've also added some dumped strings from the aforementioned gimmick files, which are loaded from a file.

Both these operations are pretty much instant. Moreover, the cutscene label loading we currently have could also be moved to the file, as it's very slow.

**Comment by vaxherd** [comment]
Nice find!
However, please remove the external file logic - I'd prefer to keep everything self-contained within the script file. I don't think this script is the sort of thing which will be run often enough that that sort of optimization is needed.
LGTM otherwise.

**Comment by RoccoDev** [comment]
Sure thing, what should I do with the dumped strings then? It's more than 2k lines so it's probably not a good idea to add them all to the script.

**Comment by vaxherd** [comment]
The hash mapping is already ~8k lines - another 2k is no big deal. Feel free to drop them in as a unit if you don't want to sort them into the existing length/lexical sort of generic strings.

**Comment by RoccoDev** [comment]
Done! I've also silenced the "Compiled gimmick hashes" text when the module is used as a library.

**Comment by vaxherd** [comment]
Looks good, thanks!

**Pull request merged**
